#!/bin/sh /etc/rc.common

START=97
start() {
	FIRSTBOOT=$(uci get system.@system[0].firstboot)
	if [ $FIRSTBOOT -eq '1' ]
	then
		load_config
	fi
	ps | grep "socket_io" | grep -v grep | awk '{print $1}' | xargs kill -s 9
	sleep 2
	socket_io &
}

stop() {
	ps | grep "socket_io" | grep -v grep | awk '{print $1}' | xargs kill -s 9
}

load_config()
{
    uci set siod.siod_id.id=$(hexdump -v -e '1/1 "%.2x"' -s $((0x1005)) -n 3 /dev/mtd6)
	uci commit siod
}